version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123w
      POSTGRES_DB: moviedb
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

  app:
    build: .
    container_name: movie-server
    restart: always
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://postgres:123w@postgres-db:5432/moviedb
    ports:
      - "6122:6122"
    command: npm run start
